// functions used by the handlebar helpers
// are marked USED BY HANDLEBAR

  //USED BY HANDLEBAR
  function strip(html){
        var tmp = document.createElement("div");    
        tmp.innerHTML = html;
        return tmp.textContent || tmp.innerText; 
  }

  //USED BY HANDLEBAR
  function commaSeparateNumber(val){
      while (/(\d+)(\d{3})/.test(val.toString())){
        val = val.toString().replace(/(\d+)(\d{3})/, '$1'+','+'$2');
      }
    return val;
    }

  //USED BY HANDLEBAR
  function makeSafeId(id){
    return id.replace(/#/g,"-hash-")
    .replace(/\//g,"-slash-")
    .replace(/\./g,"-dot-")
    .replace(/ /g,"-space-")
    .replace(/:/g,"-colon-");

  }

  function makeUnsafeId(s){
      return s.replace(/-colon-/g,":")
      .replace(/-dot-/g,".")
      .replace(/-slash-/g,"/")
      .replace(/-space-/g," ")
    .replace(/-hash-/g,"#");
  }


function trim(s){
  return s .replace(/^\s+|\s+$/g, '');
}

function getSirenURL(contextPath){
    return contextPath + "proxy/";
}

    
    function escape(s,preserveCR){
      preserveCR = preserveCR ? '&#13;' : '\n';
        s = ('' + s) /* Forces the conversion to string. */
            .replace(/&/g, '&amp;') /* This MUST be the 1st replacement. */
            .replace(/'/g, '&apos;') /* The 4 other predefined entities, required. */
            .replace(/"/g, '&quot;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            /*
            You may add other replacements here for HTML only 
            (but it's not necessary).
            Or for XML, only if the named entities are defined in its DTD.
            */ 
            .replace(/\r\n/g, preserveCR) /* Must be before the next replacement. */
            .replace(/[\r\n]/g, preserveCR);
        return s;
    }


var SindiceHelper ={};
SindiceHelper.prefixes={
"http://hcls.sindice.com/chembl:":"hcls_chembl",
"http://rdf.farmbio.uu.se/chembl/onto/#":"farmbio",
"http://data.kasabi.com/":"kasabi",
"http://schema.org/":"sorg",
"http://www.schema.org/":"sorg",
"http://schema.org/Mosque/":"sorgMosque",
"http://www.schema.org/Mosque/":"sorgMosque",
"http://schema.org/MusicAlbum/":"sorgMusicAlbum",
"http://www.schema.org/MusicAlbum/":"sorgMusicAlbum",
"http://schema.org/WPHeader/":"sorgWPHeader",
"http://www.schema.org/WPHeader/":"sorgWPHeader",
"http://schema.org/Offer/":"sorgOffer",
"http://www.schema.org/Offer/":"sorgOffer",
"http://schema.org/StructuredValue/":"sorgStructuredValue",
"http://www.schema.org/StructuredValue/":"sorgStructuredValue",
"http://schema.org/Library/":"sorgLibrary",
"http://www.schema.org/Library/":"sorgLibrary",
"http://schema.org/FoodEvent/":"sorgFoodEvent",
"http://www.schema.org/FoodEvent/":"sorgFoodEvent",
"http://schema.org/ProfilePage/":"sorgProfilePage",
"http://www.schema.org/ProfilePage/":"sorgProfilePage",
"http://schema.org/HousePainter/":"sorgHousePainter",
"http://www.schema.org/HousePainter/":"sorgHousePainter",
"http://schema.org/CreativeWork/":"sorgCreativeWork",
"http://www.schema.org/CreativeWork/":"sorgCreativeWork",
"http://schema.org/BikeStore/":"sorgBikeStore",
"http://www.schema.org/BikeStore/":"sorgBikeStore",
"http://schema.org/HighSchool/":"sorgHighSchool",
"http://www.schema.org/HighSchool/":"sorgHighSchool",
"http://schema.org/MusicPlaylist/":"sorgMusicPlaylist",
"http://www.schema.org/MusicPlaylist/":"sorgMusicPlaylist",
"http://schema.org/TVSeason/":"sorgTVSeason",
"http://www.schema.org/TVSeason/":"sorgTVSeason",
"http://schema.org/Country/":"sorgCountry",
"http://www.schema.org/Country/":"sorgCountry",
"http://schema.org/MotorcycleDealer/":"sorgMotorcycleDealer",
"http://www.schema.org/MotorcycleDealer/":"sorgMotorcycleDealer",
"http://schema.org/VeterinaryCare/":"sorgVeterinaryCare",
"http://www.schema.org/VeterinaryCare/":"sorgVeterinaryCare",
"http://schema.org/RealEstateAgent/":"sorgRealEstateAgent",
"http://www.schema.org/RealEstateAgent/":"sorgRealEstateAgent",
"http://schema.org/AdultEntertainment/":"sorgAdultEntertainment",
"http://www.schema.org/AdultEntertainment/":"sorgAdultEntertainment",
"http://schema.org/Canal/":"sorgCanal",
"http://www.schema.org/Canal/":"sorgCanal",
"http://schema.org/CityHall/":"sorgCityHall",
"http://www.schema.org/CityHall/":"sorgCityHall",
"http://schema.org/SportingGoodsStore/":"sorgSportingGoodsStore",
"http://www.schema.org/SportingGoodsStore/":"sorgSportingGoodsStore",
"http://schema.org/Rating/":"sorgRating",
"http://www.schema.org/Rating/":"sorgRating",
"http://schema.org/Mass/":"sorgMass",
"http://www.schema.org/Mass/":"sorgMass",
"http://schema.org/MedicalClinic/":"sorgMedicalClinic",
"http://www.schema.org/MedicalClinic/":"sorgMedicalClinic",
"http://schema.org/Beach/":"sorgBeach",
"http://www.schema.org/Beach/":"sorgBeach",
"http://schema.org/UserLikes/":"sorgUserLikes",
"http://www.schema.org/UserLikes/":"sorgUserLikes",
"http://schema.org/WebPage/":"sorgWebPage",
"http://www.schema.org/WebPage/":"sorgWebPage",
"http://schema.org/SkiResort/":"sorgSkiResort",
"http://www.schema.org/SkiResort/":"sorgSkiResort",
"http://schema.org/Pharmacy/":"sorgPharmacy",
"http://www.schema.org/Pharmacy/":"sorgPharmacy",
"http://schema.org/Residence/":"sorgResidence",
"http://www.schema.org/Residence/":"sorgResidence",
"http://schema.org/AudioObject/":"sorgAudioObject",
"http://www.schema.org/AudioObject/":"sorgAudioObject",
"http://schema.org/BodyOfWater/":"sorgBodyOfWater",
"http://www.schema.org/BodyOfWater/":"sorgBodyOfWater",
"http://schema.org/Park/":"sorgPark",
"http://www.schema.org/Park/":"sorgPark",
"http://schema.org/Bakery/":"sorgBakery",
"http://www.schema.org/Bakery/":"sorgBakery",
"http://schema.org/ApartmentComplex/":"sorgApartmentComplex",
"http://www.schema.org/ApartmentComplex/":"sorgApartmentComplex",
"http://schema.org/GovernmentOffice/":"sorgGovernmentOffice",
"http://www.schema.org/GovernmentOffice/":"sorgGovernmentOffice",
"http://schema.org/Physician/":"sorgPhysician",
"http://www.schema.org/Physician/":"sorgPhysician",
"http://schema.org/ElectronicsStore/":"sorgElectronicsStore",
"http://www.schema.org/ElectronicsStore/":"sorgElectronicsStore",
"http://schema.org/StadiumOrArena/":"sorgStadiumOrArena",
"http://www.schema.org/StadiumOrArena/":"sorgStadiumOrArena",
"http://schema.org/Motel/":"sorgMotel",
"http://www.schema.org/Motel/":"sorgMotel",
"http://schema.org/VideoGallery/":"sorgVideoGallery",
"http://www.schema.org/VideoGallery/":"sorgVideoGallery",
"http://schema.org/MovieRentalStore/":"sorgMovieRentalStore",
"http://www.schema.org/MovieRentalStore/":"sorgMovieRentalStore",
"http://schema.org/MusicStore/":"sorgMusicStore",
"http://www.schema.org/MusicStore/":"sorgMusicStore",
"http://schema.org/PetStore/":"sorgPetStore",
"http://www.schema.org/PetStore/":"sorgPetStore",
"http://schema.org/RiverBodyOfWater/":"sorgRiverBodyOfWater",
"http://www.schema.org/RiverBodyOfWater/":"sorgRiverBodyOfWater",
"http://schema.org/Playground/":"sorgPlayground",
"http://www.schema.org/Playground/":"sorgPlayground",
"http://schema.org/Place/":"sorgPlace",
"http://www.schema.org/Place/":"sorgPlace",
"http://schema.org/PawnShop/":"sorgPawnShop",
"http://www.schema.org/PawnShop/":"sorgPawnShop",
"http://schema.org/HomeAndConstructionBusiness/":"sorgHomeAndConstructionBusiness",
"http://www.schema.org/HomeAndConstructionBusiness/":"sorgHomeAndConstructionBusiness",
"http://schema.org/Landform/":"sorgLandform",
"http://www.schema.org/Landform/":"sorgLandform",
"http://schema.org/AboutPage/":"sorgAboutPage",
"http://www.schema.org/AboutPage/":"sorgAboutPage",
"http://schema.org/SearchResultsPage/":"sorgSearchResultsPage",
"http://www.schema.org/SearchResultsPage/":"sorgSearchResultsPage",
"http://schema.org/AutomotiveBusiness/":"sorgAutomotiveBusiness",
"http://www.schema.org/AutomotiveBusiness/":"sorgAutomotiveBusiness",
"http://schema.org/ItemAvailability/":"sorgItemAvailability",
"http://www.schema.org/ItemAvailability/":"sorgItemAvailability",
"http://schema.org/DryCleaningOrLaundry/":"sorgDryCleaningOrLaundry",
"http://www.schema.org/DryCleaningOrLaundry/":"sorgDryCleaningOrLaundry",
"http://schema.org/CatholicChurch/":"sorgCatholicChurch",
"http://www.schema.org/CatholicChurch/":"sorgCatholicChurch",
"http://schema.org/ShoppingCenter/":"sorgShoppingCenter",
"http://www.schema.org/ShoppingCenter/":"sorgShoppingCenter",
"http://schema.org/ChildCare/":"sorgChildCare",
"http://www.schema.org/ChildCare/":"sorgChildCare",
"http://schema.org/WPSideBar/":"sorgWPSideBar",
"http://www.schema.org/WPSideBar/":"sorgWPSideBar",
"http://schema.org/Airport/":"sorgAirport",
"http://www.schema.org/Airport/":"sorgAirport",
"http://schema.org/MotorcycleRepair/":"sorgMotorcycleRepair",
"http://www.schema.org/MotorcycleRepair/":"sorgMotorcycleRepair",
"http://schema.org/UserComments/":"sorgUserComments",
"http://www.schema.org/UserComments/":"sorgUserComments",
"http://schema.org/Winery/":"sorgWinery",
"http://www.schema.org/Winery/":"sorgWinery",
"http://schema.org/SportsTeam/":"sorgSportsTeam",
"http://www.schema.org/SportsTeam/":"sorgSportsTeam",
"http://schema.org/Language/":"sorgLanguage",
"http://www.schema.org/Language/":"sorgLanguage",
"http://schema.org/NutritionInformation/":"sorgNutritionInformation",
"http://www.schema.org/NutritionInformation/":"sorgNutritionInformation",
"http://schema.org/GovernmentBuilding/":"sorgGovernmentBuilding",
"http://www.schema.org/GovernmentBuilding/":"sorgGovernmentBuilding",
"http://schema.org/HealthClub/":"sorgHealthClub",
"http://www.schema.org/HealthClub/":"sorgHealthClub",
"http://schema.org/ContactPage/":"sorgContactPage",
"http://www.schema.org/ContactPage/":"sorgContactPage",
"http://schema.org/LocalBusiness/":"sorgLocalBusiness",
"http://www.schema.org/LocalBusiness/":"sorgLocalBusiness",
"http://schema.org/MusicRecording/":"sorgMusicRecording",
"http://www.schema.org/MusicRecording/":"sorgMusicRecording",
"http://schema.org/ProfessionalService/":"sorgProfessionalService",
"http://www.schema.org/ProfessionalService/":"sorgProfessionalService",
"http://schema.org/MovingCompany/":"sorgMovingCompany",
"http://www.schema.org/MovingCompany/":"sorgMovingCompany",
"http://schema.org/Optician/":"sorgOptician",
"http://www.schema.org/Optician/":"sorgOptician",
"http://schema.org/Synagogue/":"sorgSynagogue",
"http://www.schema.org/Synagogue/":"sorgSynagogue",
"http://schema.org/MusicGroup/":"sorgMusicGroup",
"http://www.schema.org/MusicGroup/":"sorgMusicGroup",
"http://schema.org/AdministrativeArea/":"sorgAdministrativeArea",
"http://www.schema.org/AdministrativeArea/":"sorgAdministrativeArea",
"http://schema.org/Pond/":"sorgPond",
"http://www.schema.org/Pond/":"sorgPond",
"http://schema.org/CheckoutPage/":"sorgCheckoutPage",
"http://www.schema.org/CheckoutPage/":"sorgCheckoutPage",
"http://schema.org/Aquarium/":"sorgAquarium",
"http://www.schema.org/Aquarium/":"sorgAquarium",
"http://schema.org/BeautySalon/":"sorgBeautySalon",
"http://www.schema.org/BeautySalon/":"sorgBeautySalon",
"http://schema.org/CivicStructure/":"sorgCivicStructure",
"http://www.schema.org/CivicStructure/":"sorgCivicStructure",
"http://schema.org/HairSalon/":"sorgHairSalon",
"http://www.schema.org/HairSalon/":"sorgHairSalon",
"http://schema.org/AmusementPark/":"sorgAmusementPark",
"http://www.schema.org/AmusementPark/":"sorgAmusementPark",
"http://schema.org/Continent/":"sorgContinent",
"http://www.schema.org/Continent/":"sorgContinent",
"http://schema.org/BookFormatType/":"sorgBookFormatType",
"http://www.schema.org/BookFormatType/":"sorgBookFormatType",
"http://schema.org/Campground/":"sorgCampground",
"http://www.schema.org/Campground/":"sorgCampground",
"http://schema.org/GroceryStore/":"sorgGroceryStore",
"http://www.schema.org/GroceryStore/":"sorgGroceryStore",
"http://schema.org/Notary/":"sorgNotary",
"http://www.schema.org/Notary/":"sorgNotary",
"http://schema.org/ScholarlyArticle/":"sorgScholarlyArticle",
"http://www.schema.org/ScholarlyArticle/":"sorgScholarlyArticle",
"http://schema.org/HobbyShop/":"sorgHobbyShop",
"http://www.schema.org/HobbyShop/":"sorgHobbyShop",
"http://schema.org/HardwareStore/":"sorgHardwareStore",
"http://www.schema.org/HardwareStore/":"sorgHardwareStore",
"http://schema.org/Embassy/":"sorgEmbassy",
"http://www.schema.org/Embassy/":"sorgEmbassy",
"http://schema.org/UserTweets/":"sorgUserTweets",
"http://www.schema.org/UserTweets/":"sorgUserTweets",
"http://schema.org/BankOrCreditUnion/":"sorgBankOrCreditUnion",
"http://www.schema.org/BankOrCreditUnion/":"sorgBankOrCreditUnion",
"http://schema.org/WebPageElement/":"sorgWebPageElement",
"http://www.schema.org/WebPageElement/":"sorgWebPageElement",
"http://schema.org/Distance/":"sorgDistance",
"http://www.schema.org/Distance/":"sorgDistance",
"http://schema.org/HinduTemple/":"sorgHinduTemple",
"http://www.schema.org/HinduTemple/":"sorgHinduTemple",
"http://schema.org/Hospital/":"sorgHospital",
"http://www.schema.org/Hospital/":"sorgHospital",
"http://schema.org/DanceEvent/":"sorgDanceEvent",
"http://www.schema.org/DanceEvent/":"sorgDanceEvent",
"http://schema.org/InternetCafe/":"sorgInternetCafe",
"http://www.schema.org/InternetCafe/":"sorgInternetCafe",
"http://schema.org/UserBlocks/":"sorgUserBlocks",
"http://www.schema.org/UserBlocks/":"sorgUserBlocks",
"http://schema.org/JewelryStore/":"sorgJewelryStore",
"http://www.schema.org/JewelryStore/":"sorgJewelryStore",
"http://schema.org/WholesaleStore/":"sorgWholesaleStore",
"http://www.schema.org/WholesaleStore/":"sorgWholesaleStore",
"http://schema.org/UserCheckins/":"sorgUserCheckins",
"http://www.schema.org/UserCheckins/":"sorgUserCheckins",
"http://schema.org/Florist/":"sorgFlorist",
"http://www.schema.org/Florist/":"sorgFlorist",
"http://schema.org/WPFooter/":"sorgWPFooter",
"http://www.schema.org/WPFooter/":"sorgWPFooter",
"http://schema.org/GardenStore/":"sorgGardenStore",
"http://www.schema.org/GardenStore/":"sorgGardenStore",
"http://schema.org/Brewery/":"sorgBrewery",
"http://www.schema.org/Brewery/":"sorgBrewery",
"http://schema.org/OfferItemCondition/":"sorgOfferItemCondition",
"http://www.schema.org/OfferItemCondition/":"sorgOfferItemCondition",
"http://schema.org/DaySpa/":"sorgDaySpa",
"http://www.schema.org/DaySpa/":"sorgDaySpa",
"http://schema.org/VideoObject/":"sorgVideoObject",
"http://www.schema.org/VideoObject/":"sorgVideoObject",
"http://schema.org/LegislativeBuilding/":"sorgLegislativeBuilding",
"http://www.schema.org/LegislativeBuilding/":"sorgLegislativeBuilding",
"http://schema.org/Store/":"sorgStore",
"http://www.schema.org/Store/":"sorgStore",
"http://schema.org/MiddleSchool/":"sorgMiddleSchool",
"http://www.schema.org/MiddleSchool/":"sorgMiddleSchool",
"http://schema.org/RecyclingCenter/":"sorgRecyclingCenter",
"http://www.schema.org/RecyclingCenter/":"sorgRecyclingCenter",
"http://schema.org/MediaObject/":"sorgMediaObject",
"http://www.schema.org/MediaObject/":"sorgMediaObject",
"http://schema.org/BusStop/":"sorgBusStop",
"http://www.schema.org/BusStop/":"sorgBusStop",
"http://schema.org/Duration/":"sorgDuration",
"http://www.schema.org/Duration/":"sorgDuration",
"http://schema.org/Movie/":"sorgMovie",
"http://www.schema.org/Movie/":"sorgMovie",
"http://schema.org/Crematorium/":"sorgCrematorium",
"http://www.schema.org/Crematorium/":"sorgCrematorium",
"http://schema.org/FurnitureStore/":"sorgFurnitureStore",
"http://www.schema.org/FurnitureStore/":"sorgFurnitureStore",
"http://schema.org/BarOrPub/":"sorgBarOrPub",
"http://www.schema.org/BarOrPub/":"sorgBarOrPub",
"http://schema.org/NightClub/":"sorgNightClub",
"http://www.schema.org/NightClub/":"sorgNightClub",
"http://schema.org/Zoo/":"sorgZoo",
"http://www.schema.org/Zoo/":"sorgZoo",
"http://schema.org/Enumeration/":"sorgEnumeration",
"http://www.schema.org/Enumeration/":"sorgEnumeration",
"http://schema.org/SeaBodyOfWater/":"sorgSeaBodyOfWater",
"http://www.schema.org/SeaBodyOfWater/":"sorgSeaBodyOfWater",
"http://schema.org/Preschool/":"sorgPreschool",
"http://www.schema.org/Preschool/":"sorgPreschool",
"http://schema.org/MusicEvent/":"sorgMusicEvent",
"http://www.schema.org/MusicEvent/":"sorgMusicEvent",
"http://schema.org/EmploymentAgency/":"sorgEmploymentAgency",
"http://www.schema.org/EmploymentAgency/":"sorgEmploymentAgency",
"http://schema.org/BusinessEvent/":"sorgBusinessEvent",
"http://www.schema.org/BusinessEvent/":"sorgBusinessEvent",
"http://schema.org/AutoRental/":"sorgAutoRental",
"http://www.schema.org/AutoRental/":"sorgAutoRental",
"http://schema.org/Intangible/":"sorgIntangible",
"http://www.schema.org/Intangible/":"sorgIntangible",
"http://schema.org/MusicVideoObject/":"sorgMusicVideoObject",
"http://www.schema.org/MusicVideoObject/":"sorgMusicVideoObject",
"http://schema.org/State/":"sorgState",
"http://www.schema.org/State/":"sorgState",
"http://schema.org/UserPlusOnes/":"sorgUserPlusOnes",
"http://www.schema.org/UserPlusOnes/":"sorgUserPlusOnes",
"http://schema.org/SportsEvent/":"sorgSportsEvent",
"http://www.schema.org/SportsEvent/":"sorgSportsEvent",
"http://schema.org/Mountain/":"sorgMountain",
"http://www.schema.org/Mountain/":"sorgMountain",
"http://schema.org/AutoBodyShop/":"sorgAutoBodyShop",
"http://www.schema.org/AutoBodyShop/":"sorgAutoBodyShop",
"http://schema.org/HVACBusiness/":"sorgHVACBusiness",
"http://www.schema.org/HVACBusiness/":"sorgHVACBusiness",
"http://schema.org/TouristInformationCenter/":"sorgTouristInformationCenter",
"http://www.schema.org/TouristInformationCenter/":"sorgTouristInformationCenter",
"http://schema.org/ClothingStore/":"sorgClothingStore",
"http://www.schema.org/ClothingStore/":"sorgClothingStore",
"http://schema.org/RadioStation/":"sorgRadioStation",
"http://www.schema.org/RadioStation/":"sorgRadioStation",
"http://schema.org/EntertainmentBusiness/":"sorgEntertainmentBusiness",
"http://www.schema.org/EntertainmentBusiness/":"sorgEntertainmentBusiness",
"http://schema.org/TelevisionStation/":"sorgTelevisionStation",
"http://www.schema.org/TelevisionStation/":"sorgTelevisionStation",
"http://schema.org/MusicVenue/":"sorgMusicVenue",
"http://www.schema.org/MusicVenue/":"sorgMusicVenue",
"http://schema.org/ItemList/":"sorgItemList",
"http://www.schema.org/ItemList/":"sorgItemList",
"http://schema.org/ItemPage/":"sorgItemPage",
"http://www.schema.org/ItemPage/":"sorgItemPage",
"http://schema.org/HealthAndBeautyBusiness/":"sorgHealthAndBeautyBusiness",
"http://www.schema.org/HealthAndBeautyBusiness/":"sorgHealthAndBeautyBusiness",
"http://schema.org/Hostel/":"sorgHostel",
"http://www.schema.org/Hostel/":"sorgHostel",
"http://schema.org/TaxiStand/":"sorgTaxiStand",
"http://www.schema.org/TaxiStand/":"sorgTaxiStand",
"http://schema.org/AnimalShelter/":"sorgAnimalShelter",
"http://www.schema.org/AnimalShelter/":"sorgAnimalShelter",
"http://schema.org/PoliceStation/":"sorgPoliceStation",
"http://www.schema.org/PoliceStation/":"sorgPoliceStation",
"http://schema.org/GatedResidenceCommunity/":"sorgGatedResidenceCommunity",
"http://www.schema.org/GatedResidenceCommunity/":"sorgGatedResidenceCommunity",
"http://schema.org/GasStation/":"sorgGasStation",
"http://www.schema.org/GasStation/":"sorgGasStation",
"http://schema.org/NGO/":"sorgNGO",
"http://www.schema.org/NGO/":"sorgNGO",
"http://schema.org/SportsClub/":"sorgSportsClub",
"http://www.schema.org/SportsClub/":"sorgSportsClub",
"http://schema.org/BedAndBreakfast/":"sorgBedAndBreakfast",
"http://www.schema.org/BedAndBreakfast/":"sorgBedAndBreakfast",
"http://schema.org/GeneralContractor/":"sorgGeneralContractor",
"http://www.schema.org/GeneralContractor/":"sorgGeneralContractor",
"http://schema.org/MovieTheater/":"sorgMovieTheater",
"http://www.schema.org/MovieTheater/":"sorgMovieTheater",
"http://schema.org/Painting/":"sorgPainting",
"http://www.schema.org/Painting/":"sorgPainting",
"http://schema.org/PerformingArtsTheater/":"sorgPerformingArtsTheater",
"http://www.schema.org/PerformingArtsTheater/":"sorgPerformingArtsTheater",
"http://schema.org/ContactPoint/":"sorgContactPoint",
"http://www.schema.org/ContactPoint/":"sorgContactPoint",
"http://schema.org/TennisComplex/":"sorgTennisComplex",
"http://www.schema.org/TennisComplex/":"sorgTennisComplex",
"http://schema.org/FinancialService/":"sorgFinancialService",
"http://www.schema.org/FinancialService/":"sorgFinancialService",
"http://schema.org/TouristAttraction/":"sorgTouristAttraction",
"http://www.schema.org/TouristAttraction/":"sorgTouristAttraction",
"http://schema.org/TrainStation/":"sorgTrainStation",
"http://www.schema.org/TrainStation/":"sorgTrainStation",
"http://schema.org/DefenceEstablishment/":"sorgDefenceEstablishment",
"http://www.schema.org/DefenceEstablishment/":"sorgDefenceEstablishment",
"http://schema.org/Church/":"sorgChurch",
"http://www.schema.org/Church/":"sorgChurch",
"http://schema.org/ComedyEvent/":"sorgComedyEvent",
"http://www.schema.org/ComedyEvent/":"sorgComedyEvent",
"http://schema.org/MobilePhoneStore/":"sorgMobilePhoneStore",
"http://www.schema.org/MobilePhoneStore/":"sorgMobilePhoneStore",
"http://schema.org/Book/":"sorgBook",
"http://www.schema.org/Book/":"sorgBook",
"http://schema.org/TVEpisode/":"sorgTVEpisode",
"http://www.schema.org/TVEpisode/":"sorgTVEpisode",
"http://schema.org/CollegeOrUniversity/":"sorgCollegeOrUniversity",
"http://www.schema.org/CollegeOrUniversity/":"sorgCollegeOrUniversity",
"http://schema.org/SportsActivityLocation/":"sorgSportsActivityLocation",
"http://www.schema.org/SportsActivityLocation/":"sorgSportsActivityLocation",
"http://schema.org/BowlingAlley/":"sorgBowlingAlley",
"http://www.schema.org/BowlingAlley/":"sorgBowlingAlley",
"http://schema.org/Table/":"sorgTable",
"http://www.schema.org/Table/":"sorgTable",
"http://schema.org/TheaterGroup/":"sorgTheaterGroup",
"http://www.schema.org/TheaterGroup/":"sorgTheaterGroup",
"http://schema.org/UserInteraction/":"sorgUserInteraction",
"http://www.schema.org/UserInteraction/":"sorgUserInteraction",
"http://schema.org/ImageObject/":"sorgImageObject",
"http://www.schema.org/ImageObject/":"sorgImageObject",
"http://schema.org/DanceGroup/":"sorgDanceGroup",
"http://www.schema.org/DanceGroup/":"sorgDanceGroup",
"http://schema.org/ComputerStore/":"sorgComputerStore",
"http://www.schema.org/ComputerStore/":"sorgComputerStore",
"http://schema.org/GovernmentOrganization/":"sorgGovernmentOrganization",
"http://www.schema.org/GovernmentOrganization/":"sorgGovernmentOrganization",
"http://schema.org/AutoDealer/":"sorgAutoDealer",
"http://www.schema.org/AutoDealer/":"sorgAutoDealer",
"http://schema.org/NailSalon/":"sorgNailSalon",
"http://www.schema.org/NailSalon/":"sorgNailSalon",
"http://schema.org/ExerciseGym/":"sorgExerciseGym",
"http://www.schema.org/ExerciseGym/":"sorgExerciseGym",
"http://schema.org/Blog/":"sorgBlog",
"http://www.schema.org/Blog/":"sorgBlog",
"http://schema.org/LiquorStore/":"sorgLiquorStore",
"http://www.schema.org/LiquorStore/":"sorgLiquorStore",
"http://schema.org/EducationalOrganization/":"sorgEducationalOrganization",
"http://www.schema.org/EducationalOrganization/":"sorgEducationalOrganization",
"http://schema.org/Dentist/":"sorgDentist",
"http://www.schema.org/Dentist/":"sorgDentist",
"http://schema.org/SingleFamilyResidence/":"sorgSingleFamilyResidence",
"http://www.schema.org/SingleFamilyResidence/":"sorgSingleFamilyResidence",
"http://schema.org/Casino/":"sorgCasino",
"http://www.schema.org/Casino/":"sorgCasino",
"http://schema.org/SocialEvent/":"sorgSocialEvent",
"http://www.schema.org/SocialEvent/":"sorgSocialEvent",
"http://schema.org/PostalAddress/":"sorgPostalAddress",
"http://www.schema.org/PostalAddress/":"sorgPostalAddress",
"http://schema.org/DepartmentStore/":"sorgDepartmentStore",
"http://www.schema.org/DepartmentStore/":"sorgDepartmentStore",
"http://schema.org/Hotel/":"sorgHotel",
"http://www.schema.org/Hotel/":"sorgHotel",
"http://schema.org/Locksmith/":"sorgLocksmith",
"http://www.schema.org/Locksmith/":"sorgLocksmith",
"http://schema.org/VisualArtsEvent/":"sorgVisualArtsEvent",
"http://www.schema.org/VisualArtsEvent/":"sorgVisualArtsEvent",
"http://schema.org/UserPageVisits/":"sorgUserPageVisits",
"http://www.schema.org/UserPageVisits/":"sorgUserPageVisits",
"http://schema.org/TattooParlor/":"sorgTattooParlor",
"http://www.schema.org/TattooParlor/":"sorgTattooParlor",
"http://schema.org/City/":"sorgCity",
"http://www.schema.org/City/":"sorgCity",
"http://schema.org/Article/":"sorgArticle",
"http://www.schema.org/Article/":"sorgArticle",
"http://schema.org/Cemetery/":"sorgCemetery",
"http://www.schema.org/Cemetery/":"sorgCemetery",
"http://schema.org/AggregateRating/":"sorgAggregateRating",
"http://www.schema.org/AggregateRating/":"sorgAggregateRating",
"http://schema.org/GeoShape/":"sorgGeoShape",
"http://www.schema.org/GeoShape/":"sorgGeoShape",
"http://schema.org/AutomatedTeller/":"sorgAutomatedTeller",
"http://www.schema.org/AutomatedTeller/":"sorgAutomatedTeller",
"http://schema.org/EventVenue/":"sorgEventVenue",
"http://www.schema.org/EventVenue/":"sorgEventVenue",
"http://schema.org/AutoPartsStore/":"sorgAutoPartsStore",
"http://www.schema.org/AutoPartsStore/":"sorgAutoPartsStore",
"http://schema.org/LakeBodyOfWater/":"sorgLakeBodyOfWater",
"http://www.schema.org/LakeBodyOfWater/":"sorgLakeBodyOfWater",
"http://schema.org/UserDownloads/":"sorgUserDownloads",
"http://www.schema.org/UserDownloads/":"sorgUserDownloads",
"http://schema.org/OceanBodyOfWater/":"sorgOceanBodyOfWater",
"http://www.schema.org/OceanBodyOfWater/":"sorgOceanBodyOfWater",
"http://schema.org/Person/":"sorgPerson",
"http://www.schema.org/Person/":"sorgPerson",
"http://schema.org/SelfStorage/":"sorgSelfStorage",
"http://www.schema.org/SelfStorage/":"sorgSelfStorage",
"http://schema.org/Reservoir/":"sorgReservoir",
"http://www.schema.org/Reservoir/":"sorgReservoir",
"http://schema.org/ArtGallery/":"sorgArtGallery",
"http://www.schema.org/ArtGallery/":"sorgArtGallery",
"http://schema.org/Recipe/":"sorgRecipe",
"http://www.schema.org/Recipe/":"sorgRecipe",
"http://schema.org/Waterfall/":"sorgWaterfall",
"http://www.schema.org/Waterfall/":"sorgWaterfall",
"http://schema.org/AutoWash/":"sorgAutoWash",
"http://www.schema.org/AutoWash/":"sorgAutoWash",
"http://schema.org/BookStore/":"sorgBookStore",
"http://www.schema.org/BookStore/":"sorgBookStore",
"http://schema.org/WPAdBlock/":"sorgWPAdBlock",
"http://www.schema.org/WPAdBlock/":"sorgWPAdBlock",
"http://schema.org/EmergencyService/":"sorgEmergencyService",
"http://www.schema.org/EmergencyService/":"sorgEmergencyService",
"http://schema.org/CollectionPage/":"sorgCollectionPage",
"http://www.schema.org/CollectionPage/":"sorgCollectionPage",
"http://schema.org/Organization/":"sorgOrganization",
"http://www.schema.org/Organization/":"sorgOrganization",
"http://schema.org/SiteNavigationElement/":"sorgSiteNavigationElement",
"http://www.schema.org/SiteNavigationElement/":"sorgSiteNavigationElement",
"http://schema.org/HomeGoodsStore/":"sorgHomeGoodsStore",
"http://www.schema.org/HomeGoodsStore/":"sorgHomeGoodsStore",
"http://schema.org/TheaterEvent/":"sorgTheaterEvent",
"http://www.schema.org/TheaterEvent/":"sorgTheaterEvent",
"http://schema.org/MensClothingStore/":"sorgMensClothingStore",
"http://www.schema.org/MensClothingStore/":"sorgMensClothingStore",
"http://schema.org/OutletStore/":"sorgOutletStore",
"http://www.schema.org/OutletStore/":"sorgOutletStore",
"http://schema.org/TireShop/":"sorgTireShop",
"http://www.schema.org/TireShop/":"sorgTireShop",
"http://schema.org/SaleEvent/":"sorgSaleEvent",
"http://www.schema.org/SaleEvent/":"sorgSaleEvent",
"http://schema.org/RoofingContractor/":"sorgRoofingContractor",
"http://www.schema.org/RoofingContractor/":"sorgRoofingContractor",
"http://schema.org/FireStation/":"sorgFireStation",
"http://www.schema.org/FireStation/":"sorgFireStation",
"http://schema.org/AutoRepair/":"sorgAutoRepair",
"http://www.schema.org/AutoRepair/":"sorgAutoRepair",
"http://schema.org/ImageGallery/":"sorgImageGallery",
"http://www.schema.org/ImageGallery/":"sorgImageGallery",
"http://schema.org/School/":"sorgSchool",
"http://www.schema.org/School/":"sorgSchool",
"http://schema.org/PostOffice/":"sorgPostOffice",
"http://www.schema.org/PostOffice/":"sorgPostOffice",
"http://schema.org/GolfCourse/":"sorgGolfCourse",
"http://www.schema.org/GolfCourse/":"sorgGolfCourse",
"http://schema.org/RVPark/":"sorgRVPark",
"http://www.schema.org/RVPark/":"sorgRVPark",
"http://schema.org/BusStation/":"sorgBusStation",
"http://www.schema.org/BusStation/":"sorgBusStation",
"http://schema.org/ParkingFacility/":"sorgParkingFacility",
"http://www.schema.org/ParkingFacility/":"sorgParkingFacility",
"http://schema.org/Thing/":"sorgThing",
"http://www.schema.org/Thing/":"sorgThing",
"http://schema.org/Electrician/":"sorgElectrician",
"http://www.schema.org/Electrician/":"sorgElectrician",
"http://schema.org/Photograph/":"sorgPhotograph",
"http://www.schema.org/Photograph/":"sorgPhotograph",
"http://schema.org/Product/":"sorgProduct",
"http://www.schema.org/Product/":"sorgProduct",
"http://schema.org/LandmarksOrHistoricalBuildings/":"sorgLandmarksOrHistoricalBuildings",
"http://www.schema.org/LandmarksOrHistoricalBuildings/":"sorgLandmarksOrHistoricalBuildings",
"http://schema.org/Event/":"sorgEvent",
"http://www.schema.org/Event/":"sorgEvent",
"http://schema.org/Map/":"sorgMap",
"http://www.schema.org/Map/":"sorgMap",
"http://schema.org/Review/":"sorgReview",
"http://www.schema.org/Review/":"sorgReview",
"http://schema.org/ToyStore/":"sorgToyStore",
"http://www.schema.org/ToyStore/":"sorgToyStore",
"http://schema.org/PerformingGroup/":"sorgPerformingGroup",
"http://www.schema.org/PerformingGroup/":"sorgPerformingGroup",
"http://schema.org/AggregateOffer/":"sorgAggregateOffer",
"http://www.schema.org/AggregateOffer/":"sorgAggregateOffer",
"http://schema.org/UserPlays/":"sorgUserPlays",
"http://www.schema.org/UserPlays/":"sorgUserPlays",
"http://schema.org/Courthouse/":"sorgCourthouse",
"http://www.schema.org/Courthouse/":"sorgCourthouse",
"http://schema.org/MedicalOrganization/":"sorgMedicalOrganization",
"http://www.schema.org/MedicalOrganization/":"sorgMedicalOrganization",
"http://schema.org/CafeOrCoffeeShop/":"sorgCafeOrCoffeeShop",
"http://www.schema.org/CafeOrCoffeeShop/":"sorgCafeOrCoffeeShop",
"http://schema.org/TravelAgency/":"sorgTravelAgency",
"http://www.schema.org/TravelAgency/":"sorgTravelAgency",
"http://schema.org/LodgingBusiness/":"sorgLodgingBusiness",
"http://www.schema.org/LodgingBusiness/":"sorgLodgingBusiness",
"http://schema.org/SubwayStation/":"sorgSubwayStation",
"http://www.schema.org/SubwayStation/":"sorgSubwayStation",
"http://schema.org/LiteraryEvent/":"sorgLiteraryEvent",
"http://www.schema.org/LiteraryEvent/":"sorgLiteraryEvent",
"http://schema.org/BuddhistTemple/":"sorgBuddhistTemple",
"http://www.schema.org/BuddhistTemple/":"sorgBuddhistTemple",
"http://schema.org/TVSeries/":"sorgTVSeries",
"http://www.schema.org/TVSeries/":"sorgTVSeries",
"http://schema.org/EducationEvent/":"sorgEducationEvent",
"http://www.schema.org/EducationEvent/":"sorgEducationEvent",
"http://schema.org/FastFoodRestaurant/":"sorgFastFoodRestaurant",
"http://www.schema.org/FastFoodRestaurant/":"sorgFastFoodRestaurant",
"http://schema.org/Corporation/":"sorgCorporation",
"http://www.schema.org/Corporation/":"sorgCorporation",
"http://schema.org/GeoCoordinates/":"sorgGeoCoordinates",
"http://www.schema.org/GeoCoordinates/":"sorgGeoCoordinates",
"http://schema.org/PublicSwimmingPool/":"sorgPublicSwimmingPool",
"http://www.schema.org/PublicSwimmingPool/":"sorgPublicSwimmingPool",
"http://schema.org/InsuranceAgency/":"sorgInsuranceAgency",
"http://www.schema.org/InsuranceAgency/":"sorgInsuranceAgency",
"http://schema.org/Quantity/":"sorgQuantity",
"http://www.schema.org/Quantity/":"sorgQuantity",
"http://schema.org/ComedyClub/":"sorgComedyClub",
"http://www.schema.org/ComedyClub/":"sorgComedyClub",
"http://schema.org/Plumber/":"sorgPlumber",
"http://www.schema.org/Plumber/":"sorgPlumber",
"http://schema.org/OfficeEquipmentStore/":"sorgOfficeEquipmentStore",
"http://www.schema.org/OfficeEquipmentStore/":"sorgOfficeEquipmentStore",
"http://schema.org/ShoeStore/":"sorgShoeStore",
"http://www.schema.org/ShoeStore/":"sorgShoeStore",
"http://schema.org/ElementarySchool/":"sorgElementarySchool",
"http://www.schema.org/ElementarySchool/":"sorgElementarySchool",
"http://schema.org/IceCreamShop/":"sorgIceCreamShop",
"http://www.schema.org/IceCreamShop/":"sorgIceCreamShop",
"http://schema.org/AccountingService/":"sorgAccountingService",
"http://www.schema.org/AccountingService/":"sorgAccountingService",
"http://schema.org/BlogPosting/":"sorgBlogPosting",
"http://www.schema.org/BlogPosting/":"sorgBlogPosting",
"http://schema.org/Attorney/":"sorgAttorney",
"http://www.schema.org/Attorney/":"sorgAttorney",
"http://schema.org/Restaurant/":"sorgRestaurant",
"http://www.schema.org/Restaurant/":"sorgRestaurant",
"http://schema.org/Festival/":"sorgFestival",
"http://www.schema.org/Festival/":"sorgFestival",
"http://schema.org/Volcano/":"sorgVolcano",
"http://www.schema.org/Volcano/":"sorgVolcano",
"http://schema.org/Sculpture/":"sorgSculpture",
"http://www.schema.org/Sculpture/":"sorgSculpture",
"http://schema.org/Energy/":"sorgEnergy",
"http://www.schema.org/Energy/":"sorgEnergy",
"http://schema.org/ChildrensEvent/":"sorgChildrensEvent",
"http://www.schema.org/ChildrensEvent/":"sorgChildrensEvent",
"http://schema.org/ConvenienceStore/":"sorgConvenienceStore",
"http://www.schema.org/ConvenienceStore/":"sorgConvenienceStore",
"http://schema.org/Museum/":"sorgMuseum",
"http://www.schema.org/Museum/":"sorgMuseum",
"http://schema.org/FoodEstablishment/":"sorgFoodEstablishment",
"http://www.schema.org/FoodEstablishment/":"sorgFoodEstablishment",
"http://schema.org/PlaceOfWorship/":"sorgPlaceOfWorship",
"http://www.schema.org/PlaceOfWorship/":"sorgPlaceOfWorship",
"http://schema.org/NewsArticle/":"sorgNewsArticle",
"http://www.schema.org/NewsArticle/":"sorgNewsArticle",
"http://schema.org/Float/":"sorgFloat",
"http://www.schema.org/Float/":"sorgFloat",
"http://schema.org/Text/":"sorgText",
"http://www.schema.org/Text/":"sorgText",
"http://schema.org/DataType/":"sorgDataType",
"http://www.schema.org/DataType/":"sorgDataType",
"http://schema.org/Date/":"sorgDate",
"http://www.schema.org/Date/":"sorgDate",
"http://schema.org/Number/":"sorgNumber",
"http://www.schema.org/Number/":"sorgNumber",
"http://schema.org/URL/":"sorgURL",
"http://www.schema.org/URL/":"sorgURL",
"http://schema.org/Integer/":"sorgInteger",
"http://www.schema.org/Integer/":"sorgInteger",
"http://schema.org/Boolean/":"sorgBoolean",
"http://www.schema.org/Boolean/":"sorgBoolean",
"http://www.w3.org/2002/12/cal/icaltzd#":"icaltzd",
"http://vocab.sindice.net/":"sindicevocab",
"http://purl.org/ontology/wo/core#":"wo",
"http://purl.org/ontology/wo/":"wo",
"http://www.facebook.com/2008/":"facebook",
"http://rdf.data-vocabulary.org/":"rdfdata",
"http://www.w3.org/1999/xhtml/microdata#":"microdata",
"http://xmlns.com/foaf/0.1/":"foaf",
"http://purl.org/dc/terms/":"dc",
"http://www.w3.org/2002/07/owl#":"owl",
"http://www.w3.org/1999/02/22-rdf-syntax-ns#":"rdf",
"http://www.w3.org/2000/01/rdf-schema#":"rdfs",
"http://www.w3.org/2004/02/skos/core#":"skos",
"http://dbpedia.org/property/":"dbp",
"http://www.w3.org/2003/01/geo/wgs84_pos#":"geo",
"http://www.w3.org/2001/XMLSchema#":"xsd",
"http://rdfs.org/sioc/ns#":"sioc",
"http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#":"d2rq",
"http://swrc.ontoware.org/ontology#":"swrc",
"http://purl.org/rss/1.0/modules/content/":"content",
"http://dbpedia.org/ontology/":"dbo",
"http://purl.org/rss/1.0/":"rss",
"http://this.invalid/test2#":"test2",
"http://dbpedia.org/resource/":"dbpedia",
"http://dbpedia.org/property/":"dbpprop",
"http://www.semanticdesktop.org/ontologies/2007/01/19/nie#":"nie",
"http://www.w3.org/2006/gen/ont#":"gen",
"http://www.w3.org/1999/xhtml#":"xhtml",
"http://purl.org/dc/terms/":"dcterms",
"http://www.ontotext.com/trree/owlim#":"owlim",
"http://www.aktors.org/ontology/portal#":"akt",
"http://www.geonames.org/ontology#":"geonames",
"http://purl.org/microformat/hmedia/":"media",
"http://www.w3.org/2002/xforms/":"xf",
"http://purl.org/dc/terms/":"dct",
"http://purl.org/dc/elements/1.1/":"dc11",
"http://www.w3.org/2002/12/cal/ical#":"ical",
"http://ontologies.ezweb.morfeo-project.org/reco/ns#":"reco",
"http://sw.deri.org/2005/08/conf/cfp.owl#":"cfp",
"http://purl.org/swan/1.2/discourse-elements/":"swande",
"http://www.w3.org/ns/org#":"org",
"http://purl.org/ontology/similarity/":"musim",
"http://purl.oclc.org/NET/sism/0.1/":"sism",
"http://www.w3.org/ns/earl#":"earl",
"http://www.w3.org/2005/xpath-functions#":"fn",
"http://creativecommons.org/ns#":"cc",
"http://www.kanzaki.com/ns/music#":"mu",
"http://dig.csail.mit.edu/TAMI/2007/amord/air#":"air",
"http://jena.hpl.hp.com/ARQ/function#":"afn",
"http://purl.org/cld/terms/":"cld",
"http://purl.org/dc/dcmitype/":"dcmit",
"http://www.w3.org/2002/12/cal/ical#":"cal",
"http://www4.wiwiss.fu-berlin.de/factbook/ns#":"factbook",
"http://www.w3.org/ns/sparql-service-description#":"sd",
"http://ontologi.es/days#":"days",
"http://rdf.freebase.com/ns/":"fb",
"http://www.ordnancesurvey.co.uk/ontology/AdministrativeGeography/v2.0/AdministrativeGeography.rdf#":"osag",
"http://purl.org/vocab/vann/":"vann",
"http://www.openarchives.org/ore/terms/":"ore",
"http://www.w3.org/2006/http#":"http",
"http://purl.org/NET/biol/botany#":"botany",
"http://rdfs.org/ns/void#":"void",
"http://purl.org/vocab/changeset/schema#":"cs",
"http://jena.hpl.hp.com/2008/tdb#":"tdb",
"http://purl.org/net/schemas/space/":"space",
"http://ontologi.es/giving#":"giving",
"http://purl.org/stuff/rev#":"rev",
"http://purl.org/ontology/po/":"po",
"http://www.w3.org/2000/10/swap/log#":"log",
"http://www.w3.org/2004/03/trix/rdfg-1/":"rdfg",
"http://purl.org/vocab/relationship/":"rel",
"http://data.semanticweb.org/ns/swc/ontology#":"swc",
"http://xmlns.com/wot/0.1/":"wot",
"http://vocab.sindice.com/xfn#":"xfn",
"http://purl.org/ontology/daia/":"daia",
"http://www.w3.org/2000/10/swap/math#":"math",
"http://purl.org/ontology/af/":"af",
"http://schemas.talis.com/2005/address/schema#":"ad",
"http://ontologies.smile.deri.ie/2009/02/27/memo#":"memo",
"http://purl.org/dc/terms/":"dcq",
"http://okkam.org/terms#":"ok",
"http://bio2rdf.org/":"bio2rdf",
"http://purl.org/net/ns/wordmap#":"wordmap",
"http://www.w3.org/2007/05/powder#":"powder",
"http://www.w3.org/2001/XMLSchema#":"xs",
"http://schemas.talis.com/2005/dir/schema#":"dir",
"http://purl.org/ontomedia/core/expression#":"ome",
"http://purl.org/goodrelations/v1#":"gr",
"http://www.holygoat.co.uk/owl/redwood/0.1/tags/":"tag",
"http://purl.org/net/rdf-money/":"money",
"http://purl.org/net/biblio#":"biblio",
"http://www.rdfabout.com/rdf/schema/usbill/":"bill",
"http://www.w3.org/1999/xhtml/vocab#":"xhv",
"http://www.openrdf.org/config/repository/sail#":"sr",
"http://test2.example.com/":"test",
"http://example.org/":"ex",
"http://umbel.org/umbel#":"umbel",
"http://purl.org/swan/1.2/discourse-relationships/":"swandr",
"http://purl.org/NET/c4dm/event.owl#":"event",
"http://xmlns.com/wordnet/1.6/":"wn",
"http://www.w3.org/2007/uwa/context/deliverycontext.owl#":"dcn",
"http://purl.org/ontology/bibo/":"bibo",
"http://www.w3.org/2000/10/swap/os#":"os",
"http://usefulinc.com/ns/doap#":"doap",
"http://wiss-ki.eu/":"wisski",
"http://vocab.deri.ie/am#":"am",
"http://www.aktors.org/ontology/support#":"akts",
"http://purl.org/NET/book/vocab#":"book",
"http://kwijibo.talis.com/":"kwijibo",
"http://www.semanlink.net/2001/00/semanlink-schema#":"sl",
"http://www.rdfabout.com/rdf/schema/politico/":"politico",
"http://www.w3.org/2007/uwa/context/hardware.owl#":"hard",
"http://purl.org/dc/dcmitype/":"dctype",
"http://www.ontologydesignpatterns.org/cp/owl/informationrealization.owl#":"ir",
"http://umbel.org/umbel/ne/":"ne",
"http://vocab.org/waiver/terms/":"wv",
"http://purl.org/swan/1.2/qualifiers/":"swanq",
"http://www.rkbexplorer.com/ontologies/coref#":"coref",
"http://purl.oclc.org/NET/nknouf/ns/bibtex#":"bibtex",
"http://www.w3.org/2000/10/swap/pim/contact#":"con",
"http://www.cogsci.princeton.edu/~wn/schema/":"wnschema",
"http://foaf.qdos.com/lastfm/schema/":"qdoslf",
"http://www.w3.org/2006/vcard/ns#":"vcard",
"http://umbel.org/umbel/sc/":"sc",
"http://www.ontologydesignpatterns.org/cp/owl/timeinterval.owl#":"ti",
"http://www.w3.org/2003/11/swrl#":"swrl",
"http://purl.org/ibis#":"ibis",
"http://d2rq.org/terms/jdbc/":"jdbc",
"http://dbpedia.org/resource/":"dbr",
"http://rdfs.org/sioc/types#":"sioct",
"http://vocab.org/bio/0.1/":"bio",
"http://purl.org/ontomedia/core/space#":"spc",
"http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#":"ncal",
"http://purl.org/ontology/mo/mit#":"mit",
"http://www.semanticdesktop.org/ontologies/2008/05/20/tmo#":"tmo",
"http://www.w3.org/2003/06/sw-vocab-status/ns#":"vs",
"http://purl.org/dc/dcam/":"dcam",
"http://conserv.deri.ie/ontology#":"conserv",
"http://www.ontologydesignpatterns.org/cp/owl/componency.owl#":"cmp",
"http://linkedgeodata.org/vocabulary#":"lgd",
"http://buzzword.org.uk/rdf/h5#":"h5",
"http://purl.org/vocab/frbr/core#":"frbr",
"http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#":"nfo",
"http://www.ontologydesignpatterns.org/cp/owl/situation.owl#":"sit",
"http://purl.org/dc/dcmitype/":"dcmitype",
"http://purl.org/ontology/myspace#":"myspo",
"http://www.rdfabout.com/rdf/schema/usfec/":"fec",
"http://purl.org/vocab/aiiso/schema#":"aiiso",
"http://ltsc.ieee.org/rdf/lomv1p0/vocabulary#":"lomvoc",
"http://ns.poundhill.com/phss/1.0/":"phss",
"http://purl.org/ontology/chord/":"chord",
"http://buzzword.org.uk/rdf/atomix#":"atomix",
"http://web-semantics.org/ns/opensocial#":"osoc",
"http://telegraphis.net/ontology/measurement/code#":"code",
"http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#":"nrl",
"http://www.w3.org/2006/timezone#":"tzont",
"http://purl.org/ontology/co/core#":"co",
"http://www.semanticdesktop.org/ontologies/2007/08/15/nao#":"nao",
"http://purl.org/swan/1.2/qualifiers/":"swanqs",
"http://umbel.org/umbel/ac/":"ac",
"http://schemas.microsoft.com/imm/":"imm",
"http://commontag.org/ns#":"ctag",
"http://resex.rkbexplorer.com/ontologies/resex#":"resex",
"http://www.w3.org/2003/11/swrlb#":"swrlb",
"http://schemas.talis.com/2005/library/schema#":"lib",
"http://www.ontologydesignpatterns.org/cp/owl/informationobjectsandrepresentationlanguages.owl#":"irrl",
"http://www.w3.org/2009/pointers#":"ptr",
"http://www.daml.org/2001/10/html/airport-ont#":"airport",
"http://purl.org/NET/lx#":"lx",
"http://purl.org/ontology/myspace#":"myspace",
"http://ramonantonio.net/doac/0.1/#":"doac",
"http://www.openrdf.org/config/repository#":"rep",
"http://www.openrdf.org/config/sail#":"sail",
"http://fliqz.com/":"urn",
"http://schemas.talis.com/2005/user/schema#":"user",
"http://www.w3.org/2004/09/fresnel#":"fresnel",
"http://langegger.at/xlwrap/vocab#":"xl",
"http://courseware.rkbexplorer.com/ontologies/courseware#":"courseware",
"http://purl.org/media/video#":"video",
"http://inference-web.org/2.0/pml-justification.owl#":"pmlj",
"http://ontologies.ezweb.morfeo-project.org/eztag/ns#":"eztag",
"http://buzzword.org.uk/rdf/xhtml-elements#":"xhe",
"http://www.openrdf.org/rdf/2009/metadata#":"meta",
"http://www.w3.org/2007/05/powder#":"wdr",
"http://purl.org/swan/1.2/citations/":"swanci",
"http://sindice.com/hlisting/0.1/":"hlisting",
"http://annotation.semanticweb.org/2004/iswc#":"iswc",
"http://purl.org/stuff/project/":"prj",
"http://ontologi.es/lang/core#":"lang",
"http://spinrdf.org/spin#":"spin",
"http://www.rdfabout.com/rdf/schema/usgovt/":"usgov",
"http://eulersharp.sourceforge.net/2003/03swap/log-rules#":"es",
"http://tipsy.googlecode.com/svn/trunk/vocab/pmt#":"pmt",
"http://purl.org/NET/scovo#":"scovo",
"http://www.w3.org/2000/10/swap/string#":"string",
"http://www.ontologydesignpatterns.org/ont/web/irw.owl#":"irw",
"http://www.w3.org/2004/06/rei#":"rei",
"http://purl.org/NET/biol/zoology#":"zoology",
"http://www.w3.org/ns/auth/rsa#":"rsa",
"http://www.w3.org/2007/uwa/context/location.owl#":"loc",
"http://purl.org/ontology/mo/":"mo",
"http://www.lingvoj.org/ontology#":"lingvoj",
"http://www.w3.org/2000/10/swap/pim/doc#":"doc",
"http://www.w3.org/2000/10/swap/list#":"list",
"http://purl.org/vocab/frbr/extended#":"frbre",
"http://purl.org/ontomedia/ext/common/being#":"omb",
"http://www.junkwork.net/xml/DocumentList#":"doclist",
"http://purl.org/swan/1.2/agents/":"swanag",
"http://ontologi.es/profiling#":"profiling",
"http://www.w3.org/ns/auth/acl#":"acl",
"http://ltsc.ieee.org/rdf/lomv1p0/lom#":"lom",
"http://www.w3.org/2000/10/swap/crypto#":"crypto",
"http://spinrdf.org/spl#":"spl",
"http://purl.org/net/provenance/ns#":"prv",
"http://www.w3.org/2003/01/geo/wgs84_pos#":"wgs84",
"http://purl.org/commerce#":"commerce",
"http://purl.org/vocab/lifecycle/schema#":"lifecycle",
"http://schemas.talis.com/2005/service/schema#":"sv",
"http://data.nasa.gov/qudt/owl/unit#":"unit",
"http://www.metadata.net/harmony/ABCSchemaV5Commented.rdf#":"abc",
"http://www.w3.org/2002/01/p3prdfv1#":"p3p",
"http://vocab.deri.ie/c4n#":"c4n",
"http://rdf.ecs.soton.ac.uk/ontology/ecs#":"ecs",
"http://purl.org/rss/1.0/modules/taxonomy/":"taxo",
"http://www.w3.org/2004/03/trix/swp-2/":"swp",
"http://purl.org/vocab/riro/sdl#":"sdl",
"http://www.w3.org/2008/content#":"cnt",
"http://www.w3.org/2007/uwa/context/java.owl#":"java",
"http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#":"nmo",
"http://purl.org/dc/terms/":"dcterm",
"http://www.affymetrix.com/community/publications/affymetrix/tmsplice#":"affy",
"http://sw.opencyc.org/concept/":"cyc",
"http://purl.org/ontomedia/ext/common/bestiary#":"omc",
"http://purl.org/NET/dady#":"dady",
"http://madskills.com/public/xml/rss/module/trackback/":"trackback",
"http://purl.org/NET/decimalised#":"ddc",
"http://purl.org/NET/c4dm/timeline.owl#":"tl",
"http://purl.org/ontomedia/ext/common/trait#":"omt",
"http://www.w3.org/2003/12/exif/ns#":"exif",
"http://data.ordnancesurvey.co.uk/id/":"osgb",
"http://www.w3.org/2006/link#":"link",
"http://www.w3.org/2007/05/powder-s#":"wdrs",
"http://diplomski.nelakolundzija.org/LTontology.rdf#":"lt",
"http://inference-web.org/2.0/pml-relation.owl#":"pmlr",
"http://buzzword.org.uk/rdf/xen#":"xen",
"http://open.vocab.org/terms/":"ov",
"http://www.w3.org/1999/xhtml/vocab/":"xhtmlvocab",
"http://topbraid.org/sparqlmotion#":"sm",
"http://www.rkbexplorer.com/ontologies/acm#":"acm",
"http://www.w3.org/2008/05/skos-xl#":"skosxl",
"http://purl.org/NET/biol/ns#":"biol",
"http://dbpedia.org/ontology/":"dbpediaowl",
"http://purl.org/ontology/similarity/":"sim",
"http://demiblog.org/vocab/oauth#":"oauth",
"http://www.w3.org/2000/10/swap/pim/contact#":"contact",
"http://purl.org/ontology/last-fm/":"lastfm",
"http://www.rkbexplorer.com/ontologies/resist#":"resist",
"http://www.ontologydesignpatterns.org/cpont/ire.owl#":"ire",
"http://www.dotnetrdf.org/leviathan#":"lfn",
"http://www.w3.org/2002/xforms/":"xforms",
"http://www.smileyontology.com/ns#":"smiley",
"http://www.w3.org/2005/01/wai-rdf/GUIRoleTaxonomy#":"wairole",
"http://www4.wiwiss.fu-berlin.de/dailymed/resource/dailymed/":"dailymed",
"http://www.w3.org/2007/uwa/context/web.owl#":"web",
"http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#":"pimo",
"http://ontologi.es/colour/vocab#":"cv",
"http://ontologi.es/like#":"like",
"http://ontologi.es/status#":"status",
"http://www.openrdf.org/config/sail/custom#":"custom",
"http://purl.org/vocab/riro/gpt#":"gpt",
"http://spinrdf.org/sp#":"sp",
"http://www.w3.org/ns/auth/cert#":"cert",
"http://www.rdfabout.com/rdf/schema/vote/":"vote",
"http://www.w3.org/2005/07/aaa#":"states",
"http://topbraid.org/sparqlmotionfunctions#":"smf",
"http://linkedevents.org/ontology/":"lode",
"http://www.w3.org/2004/02/image-regions#":"imreg",
"http://www.holygoat.co.uk/owl/redwood/0.1/tags/":"tags",
"http://purl.org/NET/acc#":"acc",
"http://eventography.org/sede/0.1/":"sede",
"http://purl.org/swan/1.2/pav/":"swanpav",
"http://data.linkedmdb.org/resource/movie/":"movie",
"http://purl.org/vocab/psychometric-profile/":"psych",
"http://sw.cyc.com/CycAnnotations_v1#":"cycann",
"http://dsnotify.org/vocab/eventset/0.1/":"evset",
"http://purl.org/NET/uri#":"uri",
"http://topbraid.org/sparqlmotionlib#":"sml",
"http://www.w3.org/2007/uwa/context/common.owl#":"common",
"http://models.okkam.org/ENS-core-vocabulary#":"okkam",
"http://www.w3.org/ns/rdfa#":"rdfa",
"http://climb.dataincubator.org/vocabs/climb/":"climb",
"http://www.w3.org/2005/Atom/":"atom",
"http://www.w3.org/2003/g/data-view#":"grddl",
"http://purl.org/vocab/riro/ddl#":"ddl",
"http://purl.org/swan/1.2/swan-commons/":"swanco",
"http://webns.net/mvcb/":"admin",
"http://www.openrdf.org/config/sail/federation#":"fed",
"http://plugin.org.uk/swh-plugins/":"swh",
"http://ontologi.es/profiling#":"pr",
"http://purl.org/vocab/resourcelist/schema#":"resource",
"http://ns.ontowiki.net/SysOnt/":"sysont",
"http://www.w3.org/ns/formats/":"formats",
"http://purl.org/media/audio#":"audio",
"http://dbpedia.org/property/":"dbpp",
"http://www.w3.org/2007/rif#":"rif",
"http://www.daml.org/2001/03/daml+oil#":"daml",
"http://dbpedia.org/class/yago/":"yago",
"http://purl.org/net/vocab/2004/03/label#":"label",
"http://www.openrdf.org/schema/sesame#":"sesame",
"http://buzzword.org.uk/rdf/personal-link-types#":"plink",
"http://a9.com/-/spec/opensearch/1.1/":"opensearch",
"http://purl.org/ontomedia/ext/common/profession#":"omp",
"http://protege.stanford.edu/system#":"protege",
"http://purl.org/NET/scovo#":"scv",
"http://purl.org/net/ldap/":"ldap",
"http://www.semanticdesktop.org/ontologies/2007/05/10/nexif#":"nexif",
"http://freedesktop.org/standards/xesam/1.0/core#":"xesam",
"http://purl.org/ontology/last-fm/":"lfm",
"http://www.openrdf.org/rdf/2009/object#":"obj",
"http://ontologies.ezweb.morfeo-project.org/ezcontext/ns#":"ezcontext",
"http://www.w3.org/2003/01/geo/wgs84_pos#":"wgspos",
"http://www.semanticdesktop.org/ontologies/2007/03/22/nco#":"nco",
"http://purl.org/NET/puc#":"puc",
"http://www.w3.org/2006/time#":"time",
"http://purl.org/ontology/symbolic-music/":"so",
"http://purl.org/ontology/last-fm/":"gob",
"http://hello.com/":"dummy",
"http://purl.org/commerce/product#":"product",
"http://scot-project.org/scot/ns#":"scot",
"http://purl.org/ontomedia/core/media#":"omm",
"http://www.w3.org/2007/uwa/context/push.owl#":"push",
"http://uriplay.org/spec/ontology/#":"play",
"http://openprovenance.org/ontology#":"opm",
"http://moat-project.org/ns#":"moat",
"http://purl.org/net/pingback/":"ping",
"http://musicontology.com/":"music",
"http://purl.org/court/def/2009/coin#":"coin",
"http://www.w3.org/2008/turtle#":"ttl",
"http://www.w3.org/2007/uwa/context/software.owl#":"soft",
"http://telegraphis.net/ontology/geography/geography#":"geographis",
"http://www.semanticdesktop.org/ontologies/2007/05/10/nid3#":"nid3",
"http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/":"bsbm",
"http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/":"drugbank",
"http://www.w3.org/2007/uwa/context/network.owl#":"net",
"http://purl.org/NET/c4dm/timeline.owl#":"timeline",
"http://opengraphprotocol.org/schema/":"og",
"http://www.w3.org/2006/03/wn/wn20/schema/":"wn20schema",
"http://web-semantics.org/ns/mysql/":"mysql",
"http://rdfs.org/sioc/actions#":"sioca",
"http://vocab.deri.ie/dcat#":"dcat",
"http://openlinksw.com/schemas/oat/":"oat",
"http://www.w3.org/2003/01/geo/wgs84_pos#":"wgs",
"http://inference-web.org/2.0/pml-provenance.owl#":"pmlp",
"http://vocab.deri.ie/rooms#":"rooms",
"http://purl.org/linguistics/gold/":"gold",
"http://zeitkunst.org/bibtex/0.1/bibtex.owl#":"bib",
"http://www.openrdf.org/config/repository/sparql#":"sparql",
"http://www.lotico.com/meetup/":"meetup",
"http://online-presence.net/opo/ns#":"opo",
"http://inference-web.org/2.0/pml-trust.owl#":"pmlt",
"http://purl.org/microformat/hmedia/":"ufmedia",
"http://purl.org/ns/meteo#":"meteo",
"http://www.w3.org/ns/sawsdl#":"sawsdl",
"http://bblfish.net/work/atom-owl/2006-06-06/#":"awol",
"http://lod.taxonconcept.org/ontology/txn.owl#":"txn",
"http://rhizomik.net/ontologies/2008/05/copyrightonto.owl#":"copyright",
"http://www.aifb.kit.edu/id/":"aifb",
"http://poshrdf.org/ns/mf#":"mf",
"http://ontologies.smile.deri.ie/pdo#":"pdo",
"http://purl.org/derecho#":"derecho",
"http://www.lotico.com/meetup/":"lotico",
"http://openean.kaufkauf.net/id/":"ean",
"http://purl.org/tripfs/2010/02#":"tripfs",
"http://www.kanzaki.com/ns/whois#":"whois",
"http://www.xbrl.org/2003/instance#":"xbrli",
"http://www.inria.fr/acacia/corese#":"cos",
"http://purl.org/NET/rulz#":"rulz",
"http://poshrdf.org/ns/posh/":"posh",
"http://www.w3.org/2007/rif-builtin-action#":"act",
"http://blogs.yandex.ru/schema/foaf/":"ya",
"http://purl.org/NET/yoda#":"yoda",
"http://semantic-mediawiki.org/swivt/1.0#":"swivt",
"http://purl.org/uF/hCard/terms/":"hcterms",
"http://purl.org/ontology/is/core#":"is",
"http://purl.org/ontology/is/quality/":"isq",
"http://purl.org/linked-data/cube#":"qb",
"http://www.semanticweb.org/ontologies/2010/6/Ontology1279614123500.owl#":"remus",
"http://west.uni-koblenz.de/ontologies/2010/07/dgfoaf.owl#":"dgfoaf",
"http://rdf.data-vocabulary.org/#":"gv",
"http://purl.org/ontology/olo/core#":"olo",
"http://purl.org/ontology/is/inst/":"isi",
"http://purl.org/ontology/is/types/":"ist",
"http://data.totl.net/game/":"game",
"http://www.semanticweb.org/ontologies/2010/6/Ontology1279614123500.owl#":"anca",
"http://purl.org/vocab/relationship/":"ref",
"http://geo.linkeddata.es/page/ontology/":"geoes",
"http://ns.aksw.org/Evolution/":"evopat",
"http://purl.org/twc/vocab/conversion/":"conv",
"http://users.utcluj.ro/~raluca/ontology/Ontology1279614123500.owl#":"lark1",
"http://purl.org/ontology/ao/core#":"ao",
"http://redfoot.net/2005/session#":"session",
"http://lsdis.cs.uga.edu/projects/semdis/opus#":"opus",
"http://purl.org/linked-data/sdmx#":"sdmx",
"http://purl.org/ontology/rec/core#":"rec",
"http://ns.inria.fr/nicetag/2009/09/25/voc#":"nt",
"http://www.kanzaki.com/ns/music#":"m"};



SindiceHelper.replacePrefixEverywhere = function(str){
    if(SindiceHelper.prefixes){
        for(uri in SindiceHelper.prefixes){
            if(SindiceHelper.prefixes.hasOwnProperty(uri)){
                var prefix = SindiceHelper.prefixes[uri];
                while(str.indexOf(uri) != -1){
                    str =  str.replace(uri,prefix+":");
                }
            }
        }
    }
    return str;
};

SindiceHelper.replacePrefix = function(str){
    if(SindiceHelper.prefixes){
    for(uri in SindiceHelper.prefixes){
        if(SindiceHelper.prefixes.hasOwnProperty(uri)){
            var prefix = SindiceHelper.prefixes[uri];
            if(str.indexOf(uri)===0){
                return str.replace(uri,prefix+":");
            }
        }       
    }
    }
    return str;
};


SindiceHelper.shortenLongWords = function(s,n,m){
  if(s.length>n){
    if(s.length>=m){
      return '<span title="'+escape(s)+'">'+escape(s.substring(0,m))+" ...</span>";
    }
  }
  return s;
};



function AjaxSirenHelper(){
}

AjaxSirenHelper.prototype = (function(){

  function _generateNameFromPath(path){
    //TODO: implement the function to derive the name from path
    return path;
  }


  return {
    getFacetPathsFromWidgetDefs: function(widgetDefs){
      var widgetDef, facetPaths = [];
      for (var i = 0; i < widgetDefs.length; i++) {
        widgetDef = widgetDefs[i];

        if (widgetDef.type === "SirenFacetWidget") {
          if (widgetDef.params.field) {
            facetPaths.push(widgetDef.params.field);
          }
        }
      }
      return facetPaths;
    },
    
    addParamsToStore: function(manager, params) {
      for (var name in params) {
        if (params.hasOwnProperty(name)) {
          manager.store.addByValue(name, params[name]);
        }
      }
    },
    
    initWidgets: function(manager, widgetDefs) {
      var i, widgetDef;
      for (i = 0; i < widgetDefs.length; i++) {
        widgetDef = widgetDefs[i];

        var options = {
          id : widgetDef.id,
          target : '#' + widgetDef.id
        };
        $.extend(true, options, widgetDef.params);


        if (widgetDef.type === "SirenFacetWidget" ||
            widgetDef.type === "SirenCurrentSearchWidget" ||
            widgetDef.type === "SirenResultCountWidget" ||
            widgetDef.type === "PagerWidget" ||
            widgetDef.type === "SirenResultsWidget" ||
            widgetDef.type === "SirenTextWidget"
            ) {

          manager.addWidget(new AjaxSolr[widgetDef.type](options));

        } else {
          throw "Not supported widget type";
        }
      }
    },
    generateSirenFacetWidgetDescription:function(paths){
      var self = this;
      var widgets = [];
      for(var i=0;i<paths.length;i++){
        widgets.push({
            id : makeSafeId(paths[i]),
            type: "SirenFacetWidget",
            params:{
              name: _generateNameFromPath.call(self,paths[i]),
              field: paths[i]
            }
        });
      }
      return widgets;
    }
  };

})();
