version: '2'

services:
  sefarad:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - .:/usr/src/app
    networks:
      - sefarad-network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.5.2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=sefarad-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - 'http.cors.allow-origin=*'
    volumes:
      - es-data:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - sefarad-network

  loader:
    build: ./examples
    volumes:
      - ./examples:/usr/src/app
    networks:
      - sefarad-network

networks:
  sefarad-network:
    driver: bridge

volumes:
  es-data: